source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

target 'XestiMonitors_Example' do

    pod 'SwiftLint',     '~> 0.24.0'
    pod 'XestiMonitors', :path => '../'

end

target 'XestiMonitorsTests' do

    pod 'XestiMonitors', :path => '../'

end
