source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'XestiMonitors_Example' do

    pod 'SwiftLint',     '~> 0.24.0'
    pod 'XestiMonitors', :path => '../'

    target 'XestiMonitorsTests' do
        inherit! :search_paths
    end

end
