author: J. G. Pusey
author_url: https://github.com/eBardX
copyright: © 2016–2018 J. G. Pusey
custom_categories:
  - name: Protocols
    children:
      - Monitor
  - name: Base Monitor Classes
    children:
      - BaseMonitor
      - BaseNotificationMonitor
  - name: Accessibility Monitor Classes
    children:
      - AccessibilityAnnouncementMonitor
      - AccessibilityElementMonitor
      - AccessibilityStatusMonitor
  - name: Application Monitor Classes
    children:
      - ApplicationStateMonitor
      - BackgroundRefreshMonitor
      - MemoryMonitor
      - ProtectedDataMonitor
      - ScreenshotMonitor
      - StatusBarMonitor
      - TimeMonitor
  - name: Device Monitor Classes
    children:
      - BatteryMonitor
      - OrientationMonitor
      - ProximityMonitor
  - name: Motion Monitor Classes
    children:
      - AccelerometerMonitor
      - AltimeterMonitor
      - DeviceMotionMonitor
      - GyroscopeMonitor
      - MagnetometerMonitor
      - MotionActivityMonitor
      - PedometerMonitor
  - name: Screen Monitor Classes
    children:
      - ScreenBrightnessMonitor
  - name: Other Monitor Classes
    children:
      - DocumentStateMonitor
      - FileSystemObjectMonitor
      - KeyboardMonitor
      - MetadataQueryMonitor
      - NetworkReachabilityMonitor
      - PasteboardMonitor
      - TextViewTextMonitor
      - UbiquitousKeyValueStoreMonitor
      - UbiquityIdentityMonitor
      - WindowMonitor
  - name: Extensions
    children:
      - CMAcceleration
github_url: https://github.com/eBardX/XestiMonitors
min_acl: public
module: XestiMonitors
readme: README.md
root_url: https://eBardX.github.io/XestiMonitors/reference/
sdk: iphoneos
theme: apple
