language: objective-c
osx_image: xcode9.2
script:
- set -o pipefail
- xcodebuild -workspace Example/XestiMonitors.xcworkspace -scheme XestiMonitors ONLY_ACTIVE_ARCH=NO build | xcpretty
- xcodebuild -workspace Example/XestiMonitors.xcworkspace -scheme XestiMonitorsTests -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.2' ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty
- xcodebuild -workspace Example/XestiMonitors.xcworkspace -scheme XestiMonitors-Example -sdk iphonesimulator11.2 ONLY_ACTIVE_ARCH=NO build | xcpretty
- pod lib lint
