os: osx
language: objective-c
osx_image: xcode11.4
env:
  global:
    - WALDO_CLI_BIN=/usr/local/bin
    - WALDO_UPLOAD_TOKEN=ee1478f86b76444e84a4afab203c7298
install:
  - curl -fLs https://github.com/waldoapp/waldo-cli/releases/download/1.6.0/waldo > ${WALDO_CLI_BIN}/waldo
  - chmod +x ${WALDO_CLI_BIN}/waldo
script:
  - cd Examples/XestiMonitorsDemo-iOS
  - ARCHIVE_PATH="$TRAVIS_BUILD_DIR"/XestiMonitorsDemo.xcarchive
  - xcodebuild -workspace XestiMonitorsDemo.xcworkspace -scheme XestiMonitorsDemo -destination 'generic/platform=iOS' -configuration Release -archivePath "$ARCHIVE_PATH" archive | xcpretty -c
  - EXPORT_PATH="$TRAVIS_BUILD_DIR"/Export
  - xcodebuild -exportArchive -archivePath "$ARCHIVE_PATH" -exportPath "$EXPORT_PATH" -exportOptionsPlist ExportOptions.plist | xcpretty -c
  - BUILD_PATH="$EXPORT_PATH"/XestiMonitorsDemo-release.ipa
  - SYMBOLS_PATH="$ARCHIVE_PATH"
  - ${WALDO_CLI_BIN}/waldo "$BUILD_PATH" "$SYMBOLS_PATH" --verbose
