os: osx
language: objective-c
osx_image: xcode11.4
env:
  global:
    - WALDO_CLI_BIN=/usr/local/bin
    - WALDO_UPLOAD_TOKEN=2adcfb0c69c0de67ec169b3552e10f38
install:
  - curl -fLs https://github.com/waldoapp/waldo-cli/releases/download/1.6.0/waldo > ${WALDO_CLI_BIN}/waldo
  - chmod +x ${WALDO_CLI_BIN}/waldo
script:
  - cd Examples/XestiMonitorsDemo-iOS
  - xcodebuild -workspace XestiMonitorsDemo.xcworkspace -scheme XestiMonitorsDemo -destination 'platform=iOS Simulator,OS=13.4.1,name=iPhone 11' -configuration Release -derivedDataPath "$TRAVIS_BUILD_DIR" build | xcpretty -c
  - BUILD_PATH="$TRAVIS_BUILD_DIR"/Build/Products/Release-iphonesimulator/XestiMonitorsDemo.app
  - ${WALDO_CLI_BIN}/waldo "$BUILD_PATH" --include_symbols
